export const PERMISSIONS = {
  // Users
  VIEW_USERS: "VIEW_USERS",
  ASSIGN_ROLE: "ASSIGN_ROLE",
  EDIT_USER: "EDIT_USER",

  // Projects
  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  VIEW_PROJECT: "VIEW_PROJECT",
  VIEW_PROJECT_COST: "VIEW_PROJECT_COST",
  DELETE_PROJECT: "DELETE_PROJECT",

  // Inventory
  VIEW_INVENTORY: "VIEW_INVENTORY",
  REQUEST_MATERIAL: "REQUEST_MATERIAL",
  APPROVE_MATERIAL: "APPROVE_MATERIAL",

  // Reports
  VIEW_REPORTS: "VIEW_REPORTS",

  // Procurement
  CREATE_RFQ: "CREATE_RFQ",
  CREATE_PO: "CREATE_PO",
  RECEIVE_GOODS: "RECEIVE_GOODS"
};
